export const ALL_SLOTS_REQUEST = "ALL_SLOTS_REQUEST";
export const ALL_SLOTS_SUCCESS = "ALL_SLOTS_SUCCESS";
export const ALL_SLOTS_FAIL = "ALL_SLOTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";